## Mastering autograd


### Example

$\mathbf{x} = \begin{bmatrix}
x_1 \\
x_2 \\
x_3 \\
x_3
\end{bmatrix}$

$
\mathbf{y} = 2 \mathbf{x}^T \mathbf{x} = 2
\begin{bmatrix}
x_1 &
x_2 &
x_3 &
x_4
\end{bmatrix}
\cdot
\begin{bmatrix}
x_1 \\
x_2 \\
x_3 \\
x_4
\end{bmatrix}
= 
2 x_1^2 +
2 x_2^2 +
2 x_3^2 +
2 x_4^2
$

$
\frac{\partial\mathbf{y}}{\partial\mathbf{x}} =
\begin{bmatrix}
4 x_1 &
4 x_2 &
4 x_3 &
4 x_4
\end{bmatrix}
$

### Code

In [33]:
import torch

In [34]:
x = torch.arange(4.0, requires_grad= True)
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [35]:
x.grad

In [36]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [38]:
y.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [10]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [12]:
x.grad == 4 * x

tensor([True, True, True, True])

In [13]:
z = 3 * torch.dot(x, x)

In [15]:
z.backward()

In [16]:
x.grad

tensor([ 0., 10., 20., 30.])

In [17]:
x.grad == (6 * x + 4 * x)

tensor([True, True, True, True])

In [22]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [23]:
y = x.sum()

In [24]:
y.backward()

In [25]:
x.grad

tensor([1., 1., 1., 1.])

In [27]:
y = x * x

In [29]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [31]:
y.backward(gradient=torch.ones(4))

In [32]:
x.grad

tensor([0., 2., 4., 6.])